General:
  lid_topic: "/rs_lidar/points"
  imu_topic: "/rs_imu"
  save_path: "/home/voxel_slam_result/"
  previous_map: ""
  bagname: "zuopaotai"
  lidar_type: 4
  blind: 0.5
  point_filter_num: 1

  # AC1
  extrinsic_tran: [0.0106, 0.0099, -0.0155] 
  extrinsic_rota: [1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]
  
  # Meta
  # extrinsic_tran: [ -0.030219, 0.02354, 0.0 ]
  # extrinsic_rota: [ 0.00385925, -0.99998828, -0.00292233,
  #                 0.00085436,  0.00292565, -0.99999536,
  #                 0.99999219,  0.00385673,  0.00086564]   

  # Airy
  # extrinsic_tran: [ 0.00418, 0.00425, -0.00446 ]
  # extrinsic_rota: [ 0., -1., 0.,
  #                -1., 0., 0.,
  #                0., 0., -1. ]

  # E1
  # extrinsic_tran: [ 0.0042744, -0.01575, -0.011212]
  # extrinsic_rota: [ -0.0, -1, -0.0,
  #                   0,  0.0,  1,
  #                   -1,  0.0, -0 ]


  is_save_map: 0

Odometry:
  cov_gyr: 0.01 # 0.01
  cov_acc: 1
  rdw_gyr: 0.0001
  rdw_acc: 0.0001
  down_size: 0.3
  beam_err: 0.01
  dept_err: 0.01
  voxel_size: 1
  min_eigen_value: 0.0025
  degrade_bound: 100
  point_notime: 0

LocalBA:
  win_size: 10
  max_layer: 2 # 1
  cov_gyr: 0.01 # 0.01
  cov_acc: 1
  rdw_gyr: 0.0001
  rdw_acc: 0.0001
  min_ba_point: 1
  plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
  imu_coef: 0.0001
  thread_num: 5

Loop:
  jud_default: 0.45
  icp_eigval: 15
  ratio_drift: 0.01
  curr_halt: 10
  prev_halt: 10
  acsize: 2
  mgsize: 2
  isHighFly: 0

GBA:
  voxel_size: 2
  min_eigen_value: 0.01
  eigen_value_array: [9.0, 9.0, 9.0, 9.0]
  total_max_iter: 3
